default_stages: [pre-commit]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        name: Ruff check
        description: "Run 'ruff check' for extremely fast Python linting"

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.383
    hooks:
      - id: pyright
        name: Pyright type check
        description: "Type Check by Pyright"
